
testEnv = Environment(toolpath = ['#/../../scons'], tools=['mcucpp'])


tests = [\
	'Ip4ProtocolTest.cpp',
	'NetBuffer.cpp',
	'Arp.cpp',
	'RxTxQueue.cpp',
	]
	

test_result = testEnv.Test('net_test', tests)
testEnv.Alias("NetTests", test_result)