
testEnv = Environment(toolpath = ['#/../../scons'], tools=['mcucpp'])


tests = [\
	'Ip4ProtocolTest.cpp',
	'NetBuffer.cpp',
	'Arp.cpp',
	'RxTxQueue.cpp',
	]
	
sources = [\
	'#/../../mcucpp/net/src/net_buffer.cpp',
	'#/../../mcucpp/net/src/Ip4Protocol.cpp',
	'#/../../mcucpp/net/src/ArpProtocol.cpp',
	'#/../../mcucpp/net/src/NetDispatch.cpp'
	
	]

test_result = testEnv.Test('net_test', tests + sources)

Default(test_result)
testEnv.Alias("NetTests", test_result)