Import('McucppHome')

testEnv = Environment(toolpath = ["%s/scons" % McucppHome], tools=['mcucpp'])
testEnv.Append(CPPPATH = ['#/inc', '#/./'])

tests = ['tests.cpp']

test_result = testEnv.Test('test_result', tests)

testEnv.Alias("Tests", test_result)