
testEnv = Environment(toolpath = ['#/scons'], tools=['mcucpp'])

testEnv.Append(CPPPATH = '#/./')

tests = testEnv.Object(testEnv.Glob('*.cpp'))

test_result = testEnv.Test('mcucpp_test', tests)
testEnv.Alias("UnitTests", test_result)