
testEnv = Environment(toolpath = ['#/scons'], tools=['mcucpp'])

tests = [\
	'7Segments.cpp', 
	'BinaryStream.cpp',
	'containers.cpp',
	'crc.cpp',
	'DelegateTest.cpp',
	'DispatcherTest.cpp',
	'DivTest.cpp',
	'encoding.cpp',
	'fixedpoint.cpp',
	'FormatWriter.cpp',
	'istream_test.cpp',
	'PinList.cpp',
	'timers.cpp',
	'UsartTests.cpp',
	'saturated.cpp'
	]

test_result = testEnv.Test('mcucpp_test_result', tests)
testEnv.Alias("UnitTests", test_result)