import os


armEnv = Environment(DEVICE_NAME = 'stm32f407', 
	toolpath = ['#/scons', '#../../scons'], 
	tools=['mcucpp'])

armEnv.Append(LINKFLAGS = ["-nostdlib"])
armEnv.Append(CCFLAGS = ["-O3", "-finline-limit=60"])

app_objects = armEnv.Object(['main.cpp'])

elf = armEnv.Program('Stm32f3HwTest', app_objects)
lss = armEnv.Disassembly(elf)
hex = armEnv.Hex(elf)
